-- - ==============================================================================================================================

insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('EKU',  'PROV03',  'municipality', 'Ekurhuleni', 'East Rand');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT421',  'PROV03',  'municipality','Emfuleni', 'Vereeniging');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT422',  'PROV03',  'municipality','Midvaal', 'Meyerton');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT423',  'PROV03',  'municipality','Lesedi', 'Heidelberg');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT481',  'PROV03',  'municipality','Mogale City', 'Krugersdorp');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT482',  'PROV03',  'municipality','Randfontein', 'Randfontein');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT483',  'PROV03',  'municipality','Westonaria', 'Westonaria');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('GT484',  'PROV03',  'municipality','Merafong City', 'Carletonville');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('JHB',  'PROV03',  'municipality', 'City of Johannesburg', 'Johannesburg');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code, demarcation_name, demarcation_capital) values('TSH', 'PROV03', 'municipality', 'Tshwane Metro', 'Pretoria');

-- - ==============================================================================================================================

insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700001', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700002', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700003', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700004', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700005', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700006', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700007', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700008', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700009', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700010', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700011', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700012', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700013', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700014', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700015', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700016', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700017', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700018', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700019', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700020', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700021', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700022', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700023', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700024', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700025', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700026', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700027', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700028', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700029', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700030', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700031', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700032', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700033', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700034', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700035', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700036', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700037', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700038', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700039', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700040', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700041', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700042', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700043', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700044', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700045', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700046', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700047', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700048', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700049', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700050', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700051', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700052', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700053', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700054', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700055', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700056', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700057', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700058', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700059', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700060', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700061', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700062', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700063', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700064', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700065', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700066', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700067', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700068', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700069', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700070', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700071', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700072', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700073', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700074', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700075', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700076', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700077', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700078', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700079', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700080', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700081', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700082', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700083', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700084', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700085', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700086', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700087', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700088', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700089', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700090', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700091', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700092', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700093', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700094', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700095', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700096', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700097', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700098', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700099', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700100', 'EKU', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79700101', 'EKU', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201001', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201002', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201003', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201004', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201005', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201006', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201007', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201008', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201009', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201010', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201011', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201012', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201013', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201014', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201015', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201016', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201017', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201018', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201019', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201020', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201021', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201022', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201023', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201024', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201025', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201026', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201027', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201028', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201029', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201030', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201031', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201032', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201033', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201034', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201035', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201036', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201037', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201038', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201039', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201040', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201041', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201042', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201043', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201044', 'GT421', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74201045', 'GT421', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202001', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202002', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202003', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202004', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202005', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202006', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202007', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202008', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202009', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202010', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202011', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202012', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202013', 'GT422', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74202014', 'GT422', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203001', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203002', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203003', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203004', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203005', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203006', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203007', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203008', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203009', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203010', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203011', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203012', 'GT423', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74203013', 'GT423', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801001', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801002', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801003', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801004', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801005', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801006', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801007', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801008', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801009', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801010', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801011', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801012', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801013', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801014', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801015', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801016', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801017', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801018', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801019', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801020', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801021', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801022', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801023', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801024', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801025', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801026', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801027', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801028', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801029', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801030', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801031', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801032', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801033', 'GT481', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74801034', 'GT481', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802001', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802002', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802003', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802004', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802005', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802006', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802007', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802008', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802009', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802010', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802011', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802012', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802013', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802014', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802015', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802016', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802017', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802018', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802019', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802020', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802021', 'GT482', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74802022', 'GT482', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803001', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803002', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803003', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803004', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803005', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803006', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803007', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803008', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803009', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803010', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803011', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803012', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803013', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803014', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803015', 'GT483', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74803016', 'GT483', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804001', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804002', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804003', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804004', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804005', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804006', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804007', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804008', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804009', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804010', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804011', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804012', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804013', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804014', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804015', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804016', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804017', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804018', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804019', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804020', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804021', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804022', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804023', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804024', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804025', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804026', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804027', 'GT484', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('74804028', 'GT484', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800001', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800002', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800003', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800004', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800005', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800006', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800007', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800008', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800009', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800010', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800011', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800012', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800013', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800014', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800015', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800016', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800017', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800018', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800019', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800020', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800021', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800022', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800023', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800024', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800025', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800026', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800027', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800028', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800029', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800030', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800031', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800032', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800033', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800034', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800035', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800036', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800037', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800038', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800039', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800040', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800041', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800042', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800043', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800044', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800045', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800046', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800047', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800048', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800049', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800050', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800051', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800052', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800053', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800054', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800055', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800056', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800057', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800058', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800059', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800060', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800061', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800062', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800063', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800064', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800065', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800066', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800067', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800068', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800069', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800070', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800071', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800072', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800073', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800074', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800075', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800076', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800077', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800078', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800079', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800080', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800081', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800082', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800083', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800084', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800085', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800086', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800087', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800088', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800089', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800090', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800091', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800092', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800093', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800094', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800095', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800096', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800097', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800098', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800099', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800100', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800101', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800102', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800103', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800104', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800105', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800106', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800107', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800108', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800109', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800110', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800111', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800112', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800113', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800114', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800115', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800116', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800117', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800118', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800119', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800120', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800121', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800122', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800123', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800124', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800125', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800126', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800127', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800128', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800129', 'JHB', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79800130', 'JHB', 'ward');


-- - ==============================================================================================================================

	
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900001', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900002', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900003', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900004', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900005', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900006', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900007', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900008', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900009', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900010', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900011', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900012', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900013', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900014', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900015', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900016', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900017', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900018', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900019', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900020', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900021', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900022', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900023', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900024', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900025', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900026', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900027', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900028', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900029', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900030', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900031', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900032', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900033', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900034', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900035', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900036', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900037', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900038', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900039', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900040', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900041', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900042', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900043', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900044', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900045', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900046', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900047', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900048', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900049', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900050', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900051', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900052', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900053', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900054', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900055', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900056', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900057', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900058', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900059', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900060', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900061', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900062', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900063', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900064', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900065', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900066', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900067', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900068', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900069', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900070', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900071', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900072', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900073', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900074', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900075', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900076', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900077', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900078', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900079', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900080', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900081', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900082', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900083', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900084', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900085', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900086', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900087', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900088', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900089', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900090', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900091', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900092', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900093', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900094', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900095', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900096', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900097', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900098', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900099', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900100', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900101', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900102', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900103', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900104', 'TSH', 'ward');
insert into demarcation(demarcation_id, demarcation_parent, demarcationtype_code) values('79900105', 'TSH', 'ward');


